name: conda_env
dependencies:
  - python=3.8
  - ffmpeg
  - cmake
  - pip
  - uvicorn
  - pytorch=1.7.1
  - torchvision
  - cudatoolkit=11.0
  - numpy
  - ftfy
  - regex
  - tqdm
  - scikit-image
  - aiofiles==0.6.0
  - black
